import random

WINDOW_WIDTH = 500
WINDOW_HEIGHT = 500

SCALE_X = 5
SCALE_Y = 5

WIDTH = int(WINDOW_WIDTH / SCALE_X)
HEIGHT = int(WINDOW_HEIGHT / SCALE_Y)

RANDOM = random.SystemRandom()
NUMBER_OF_PARTICLES = 4
MOVEMENT_WORKER_THREADS = 1
RAY_CAST_WORKER_THREADS = 2
